### ISSUE TITLE
Question about DICE score in the implementation

### ISSUE THREAD

**Issue by caodoanh2001** [nauyan/NC-Net#3]
Hi, thank you for the good work.

However, when I read the evaluation part in your code, you exactly compute DICE1 (traditional DICE) rather than DICE2 (compute DICE per nuclei).

In [verify.py](https://github.com/nauyan/NC-Net/blob/master/verify.py), line (36) https://github.com/nauyan/NC-Net/blob/0e89237c3af61d0a8fc0bd723831398225e9f983/verify.py#L36, you use `get_dice_1()` to compute DICE, not `get_dice_2()`.

However, in the paper, you mentioned that you used DICE2. The results between DICE1 and DICE2 are much different. I am confused by this. Can you help me to explain this?

Thank you very much.

**Comment by nauyan** [comment]
@caodoanh2001 Thank you for pointing out the mistake. For comparison purposes, we have used the [stats_utils.py](https://github.com/vqdang/hover_net/blob/master/metrics/stats_utils.py) was used for Evaluation by Hover-Net authors which has both DICE1 and DICE2 function implemented but for reporting results they have used DICE1 only. Therefore, for comparison with multiple models, we have also opted for the DICE1 score.

**Comment by caodoanh2001** [comment]
Thank you very much for the immediate reply, I got it.

Can I have one more question? I saw your paper reported the results of HoVer-Net lower than the original paper on CoNSeP dataset.
HoVer-Net reported 0.853, 0.571, 0.702, 0.778 and 0.547 in terms of DICE, AJI, DQ, SQ and PQ, respectively.
However, your paper reported that they are 0.831, 0.510, 0.632, 0.758, 0.480. It seems to be much lower.
I also acknowledge that you reproduced the HoVer-Net on CoNSeP dataset. But I am confusing why they were much lower, even though you stated that the reproduction was followed the recommended parameters by HoVer-Net authors.
Could you help me to explain why?

Thank you very much.

**Comment by nauyan** [comment]
For all the datasets i.e. PanNuke, Lizard, and CoNSeP we were not able to replicate results. The main reason why replication is not possible is because of using different hardware (GPUs) and different minor versions of libraries. 

In addition to this, the results reported on the Hover-Net paper were from the tensorflow version of the model however the replication that I performed on Hover-Net was using the Pytorch version of the model.

**Comment by caodoanh2001** [comment]
Thank you very much. I think it is clear now.

**Comment by caodoanh2001** [comment]
Hi @nauyan,
Sorry for bothering you again. But I think it would be great if:
1. You can provide the checkpoints for three datasets (currently the links can not be accessed, 404 error).
2. You can explain how you can implement the Hover-Net (re-train by using the PyTorch version provided by Hover-Net authors or implement it by yourself). Because in the paper you only mentioned that reproducing by using recommended parameters.

Thank you very much!

**Comment by nauyan** [comment]
@caodoanh2001 for hovernet refer to the original repository for instructions. https://github.com/vqdang/hover_net/.

I will share the updated model weight link in a couple of days.
