### ISSUE TITLE
Trained model checkpoints missing

### ISSUE THREAD

**Issue by neoyinzhanghan** [nauyan/NC-Net#5]
Hi!

Thank you so much for putting together this package!
My lab is working on a nuclei instance segmentation for the pannuke dataset and we are hoping to use your model checkpoints.
The link in your README.md file leads to a 404 page, and the checkpoints folder is currently empty with only a gitkeep file.
Would the checkpoints please be able to be provided?

**Comment by nauyan** [comment]
@neoyinzhanghan apologies. I did not get the chance to update the URL of checkpoints. Here is the updated link: https://nustedupk0-my.sharepoint.com/:f:/g/personal/srashid_dphd19seecs_student_nust_edu_pk/Einy-z7qkNdJiHhdK7MvSi4BmgkeQ8Mt9G4pmwIaEnceVA?e=RWBiZe
